apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: aymane2001/order:tag
        resources:
          limits:
            memory: "500Mi"
            cpu: "5G"
        ports:
        - containerPort: 8081